# BÀI TẬP LỚN: PHÂN TÍCH CHUỖI THỜI GIAN GIÁ VÀNG & TỶ GIÁ USD/VND
**Nhóm:** 13 | **Lớp:** DT11

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from logic_phantich import GoldDataAnalyzer, GoldVisualizer

# Khởi tạo Object từ Class OOP
analyzer = GoldDataAnalyzer(nam_bat_dau=2023)
df = analyzer.tai_va_xu_ly_du_lieu()

# Hiển thị 5 dòng đầu tiên
df.head()

,Ngày,Giá_Vàng_TG_USD,Tỷ_Giá_USD_VND,Giá_Quy_Đổi_Triệu_Đồng,Giá_SJC_Triệu_Đồng,Chênh_Lệch_SJC_TG,SMA_7,SMA_30,Lợi_Suất_%,Tháng_Năm
0,2023-01-02,1839.7,23610.0,52.37,55.27,2.9,55.27,55.27,NaN,2023-01
1,2023-01-03,1839.7,23610.0,52.37,55.27,2.9,55.27,55.27,0.00,2023-01
2,2023-01-04,1852.8,23515.0,52.53,55.43,2.9,55.32,55.32,0.29,2023-01
3,2023-01-05,1834.8,23510.0,52.01,54.91,2.9,55.22,55.22,-0.94,2023-01
4,2023-01-06,1864.2,23475.0,52.76,55.66,2.9,55.31,55.31,1.37,2023-01

In [2]:
# 1. Thống kê tổng quan các chỉ số
print("--- THỐNG KÊ MÔ TẢ ---")
display(df.describe())

# 2. Giá trị trung bình theo Tháng
print("\n--- GIÁ SJC TRUNG BÌNH THEO THÁNG ---")
df_monthly = df.groupby('Tháng_Năm')['Giá_SJC_Triệu_Đồng'].agg(['mean', 'min', 'max', 'std']).reset_index()
display(df_monthly.tail(6))

--- THỐNG KÊ MÔ TẢ ---

,Ngày,Giá_Vàng_TG_USD,Tỷ_Giá_USD_VND,Giá_Quy_Đổi_Triệu_Đồng,Giá_SJC_Triệu_Đồng,Chênh_Lệch_SJC_TG,SMA_7,SMA_30,Lợi_Suất_%
count,942,942.000000,942.000000,942.000000,942.000000,9.420000e+02,942.000000,942.000000,941.000000
mean,2024-10-22 12:33:37.834394880,2929.597134,25168.905520,89.925966,92.825966,2.900000e+00,92.553439,91.591486,0.107078
min,2023-01-02 00:00:00,1808.800000,23427.000000,51.660000,54.560000,2.900000e+00,55.190000,55.220000,-11.410000
25%,2023-11-27 06:00:00,2014.350000,24362.500000,58.795000,61.695000,2.900000e+00,61.630000,61.095000,-0.420000
50%,2024-10-21 12:00:00,2628.950000,25393.500000,79.540000,82.440000,2.900000e+00,82.420000,81.355000,0.120000
75%,2025-09-17 18:00:00,3682.100000,26190.000000,117.075000,119.975000,2.900000e+00,119.275000,113.532500,0.740000
max,2026-08-15 00:00:00,5318.400000,26425.000000,167.020000,169.920000,2.900000e+00,166.250000,162.170000,6.330000
std,NaN,994.026573,1002.920822,33.534324,33.534324,5.109739e-14,33.455065,33.267393,1.216628

--- GIÁ SJC TRUNG BÌNH THEO THÁNG ---

   Tháng_Năm        mean     min     max       std
38   2026-03  156.555455  141.86  169.12  9.526071
39   2026-04  152.630909  147.19  156.93  2.541698
40   2026-05  148.440952  143.89  152.56  2.705284
41   2026-06  137.010000  129.26  145.05  5.070500
42   2026-07  131.933913  129.06  134.62  1.581477
43   2026-08  138.473636  130.76  141.80  3.671039

In [3]:
# Gọi biểu đồ tương tác từ Class GoldVisualizer
fig1 = GoldVisualizer.ve_bieu_do_duong_va_vung(df)
fig1.show()

fig2 = GoldVisualizer.ve_heatmap_tuong_quan_plotly(df)[0]
fig2.show()